events {
	worker_connections 768;
}
pid /var/run/nginx/nginx.pid;
http {
    # This is a key line for streaming. It disables buffering for all proxy connections.
    proxy_buffering off;
    proxy_cache off;
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    server {
        listen 8080;
        location / {
            # Forward to app service
            proxy_pass ${BACKEND_SERVICE};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # These headers are vital for keeping the connection open, especially for SSE.
            proxy_set_header Connection '';
            proxy_http_version 1.1;

            # Prevents Nginx from sending a "chunked" Transfer-Encoding header.
            # While sometimes useful, it can interfere with certain clients or protocols.
            chunked_transfer_encoding off;
        }
    }
}
